### PR TITLE
Update aboutMe.yml

### PR DESCRIPTION
**Pull request by cathyvu**

### CODE REVIEW

**Comment by notionparallax** [comment]
Hi Cathy. You're trying to get me to accept your changes into my repo, rather than adding them to your own. 
You need to commit to your own master branch.
This kind of thing is a lot less confusing on the command line.

**Comment by skinnercath** [comment]
I have no idea what you're talking about.

Please don't call me Cathy

**Comment by notionparallax** [comment]
@skinnercath I think I sent you this by mistake, It was supposed to go to @cathyvu

**Comment by skinnercath** [comment]
I see! Well, as you were then...
good thing you didn't actually call me Cathy

**Pull request closed without merging**
